Resources:
  MySecureInstance:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1d
      ImageId: ami-00068cd7555f543d5
      InstanceType: t2.micro
      SecurityGroups:
        # we reference the output here, using the Fn::ImportValue function
        - !ImportValue SSHAdminCompanyWide
        - !ImportValue GlobalWSAcessGroup
#this was created in the 0-create-ssh-security-group.yaml file.
#It was exported so it can be used in other stacks.
