Parameters:
  EnyType:
    Description: Please identify if this is test or production
    Type: String
    AllowedValues:
      - prod
      - test
  KeyName:
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance.
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    #http://checkip.amazonaws.com/
Resources:
  # !Ref a keyname we already have in AWS. Security groups are referenced below.
  CFInstance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-00068cd7555f543d5
      AvailabilityZone: us-east-1b
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref AdminLoginGroup
        - !Ref WebserverAccessGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum install httpd
          sudo systemctl enable httpd
          sudo systemctl start httpd

  AdminLoginGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access for admins
      SecurityGroupIngress:
        # only allowing my IP to access port 22.
      - CidrIp: 128.229.4.22/32
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  WebserverAccessGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable users to access website
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80

Outputs:
    StackSSHSecurityGroup:
      Description: The SSH Security Group for our Company
      Value: !Ref AdminLoginGroup
    #need the export line to use with other stacks.
      Export:
        Name: SSHAdminCompanyWide
    StackWebServerAccessGroup:
      Description: This is a global group to allow traffic to the server.
      Value: !Ref WebserverAccessGroup
      Export:
        Name: GlobalWSAcessGroup
